apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service hello-lb"]'
  labels:
    app: helloworld
    istiosubset: blue
  name: helloworld
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        istiosubset: blue
    spec:
      containers:
        - image: 'gcr.io/spinbg/helloworld:v1'
          imagePullPolicy: Always
          name: helloworld
          ports:
            - containerPort: 6000
          readinessProbe:
            httpGet:
              path: /
              port: 6000
            initialDelaySeconds: 3
            periodSeconds: 3
